version: '3.7'
services:
  host-x509-certificate-exporter:
    image: ghcr.io/camalot/host-x509-certificate-exporter:latest
    hostname: host-x509-certificate-exporter
    container_name: host-x509-certificate-exporter
    restart: unless-stopped
    network_mode: bridge
    ports:
    - 8932:8932
    volumes:
    - /path/to/config:/app/config
    environment:
      X509_CONFIG_FILE: /app/config/.configuration.yaml
      X509_CONFIG_METRICS_PORT: "8932"
      X509_CONFIG_METRICS_POLLING_INTERVAL: "43200"
      X509_CONFIG_HOST_1: host1.home.local:443
      X509_CONFIG_HOST_2: host2.home.local:443
